[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/countries"
  to = "https://restcountries.com/v3.1/all?fields=name,cca2,idd"
  status = 200
  force = true

[[redirects]]
  from = "/api/ipinfo"
  to = "https://ipwho.is/"
  status = 200
  force = true

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/api/otp/send"
  to = "/.netlify/functions/otp-send"
  status = 200

[[redirects]]
  from = "/api/otp/verify"
  to = "/.netlify/functions/otp-verify"
  status = 200

[[redirects]]
  from = "/submit-form"
  to = "/.netlify/functions/submit-form"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
